stages:
  - dev-deploy
  - prod-deploy

# --- SHEN STANDALONE ---

build_and_run_shen_dev:
  stage: dev-deploy
  tags:
    - frontend-dev-001
  when: manual
  script:
    - docker build -t shen-standalone .
    - sh deploy.sh || echo "No deploy.sh, continuing..."
    - docker rm -f shen-standalone || true
    - docker run --name shen-standalone --restart always -p 3006:3000 -d shen-standalone

build_and_run_shen_prod:
  stage: prod-deploy
  tags:
    - frontend-prod-001
  when: manual
  script:
    - docker build -t shen-standalone -f Dockerfile_Prod .
    - sh deploy.sh || echo "No deploy.sh, continuing..."
    - docker rm -f shen-standalone || true
    - docker run --name shen-standalone --restart always -p 3006:3000 -d shen-standalone
